"""
Comprehensive Monitoring and Analytics System for AirOne Professional
Provides real-time monitoring, advanced analytics, and comprehensive reporting
"""

import asyncio
import time
import json
import csv
from datetime import datetime, timedelta
from typing import Dict, List, Any, Optional, Callable
import threading
import queue
import statistics
from collections import defaultdict, deque
import psutil
import GPUtil
import sqlite3
import pandas as pd
import numpy as np
from dataclasses import dataclass, asdict
from enum import Enum
import logging
from functools import wraps
import hashlib
import secrets
import matplotlib.pyplot as plt
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.express as px
from scipy import stats
import warnings
warnings.filterwarnings('ignore')


# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


class MetricType(Enum):
    """Types of metrics that can be monitored"""
    PERFORMANCE = "performance"
    SECURITY = "security"
    SYSTEM = "system"
    APPLICATION = "application"
    CUSTOM = "custom"


class AlertSeverity(Enum):
    """Severity levels for alerts"""
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"
    EMERGENCY = "emergency"


@dataclass
class Metric:
    """Represents a single metric measurement"""
    name: str
    value: float
    timestamp: datetime
    source: str
    metric_type: MetricType
    tags: Optional[Dict[str, str]] = None
    unit: Optional[str] = None


@dataclass
class Alert:
    """Represents an alert generated by the system"""
    id: str
    metric_name: str
    severity: AlertSeverity
    message: str
    timestamp: datetime
    value: float
    threshold: float
    tags: Optional[Dict[str, str]] = None


class MetricsCollector:
    """Collects and stores metrics from various system components"""
    
    def __init__(self, retention_hours: int = 24):
        self.retention_period = timedelta(hours=retention_hours)
        self.metrics_buffer = deque(maxlen=10000)  # Circular buffer for recent metrics
        self.alerts_buffer = deque(maxlen=1000)    # Circular buffer for recent alerts
        self.metric_store = defaultdict(list)      # Store metrics by name
        self.alert_callbacks = []
        self.lock = threading.Lock()
        
        # Initialize database for persistent storage
        self.db_conn = sqlite3.connect("monitoring.db", check_same_thread=False)
        self._init_database()
        
        logger.info(f"Metrics collector initialized with {retention_hours} hour retention")
    
    def _init_database(self):
        """Initialize the monitoring database"""
        cursor = self.db_conn.cursor()
        
        # Create metrics table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS metrics (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                value REAL NOT NULL,
                timestamp TEXT NOT NULL,
                source TEXT NOT NULL,
                metric_type TEXT NOT NULL,
                tags TEXT,
                unit TEXT
            )
        """)
        
        # Create alerts table
        cursor.execute("""
            CREATE TABLE IF NOT EXISTS alerts (
                id TEXT PRIMARY KEY,
                metric_name TEXT NOT NULL,
                severity TEXT NOT NULL,
                message TEXT NOT NULL,
                timestamp TEXT NOT NULL,
                value REAL NOT NULL,
                threshold REAL NOT NULL,
                tags TEXT
            )
        """)
        
        # Create indexes for performance
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_metrics_timestamp ON metrics(timestamp)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_metrics_name ON metrics(name)")
        cursor.execute("CREATE INDEX IF NOT EXISTS idx_alerts_timestamp ON alerts(timestamp)")
        
        self.db_conn.commit()
        logger.info("Monitoring database initialized")
    
    def collect_metric(self, name: str, value: float, source: str, 
                      metric_type: MetricType, unit: Optional[str] = None,
                      tags: Optional[Dict[str, str]] = None):
        """Collect a metric measurement"""
        metric = Metric(
            name=name,
            value=value,
            timestamp=datetime.utcnow(),
            source=source,
            metric_type=metric_type,
            tags=tags,
            unit=unit
        )
        
        with self.lock:
            # Add to in-memory buffer
            self.metrics_buffer.append(metric)
            
            # Add to named store
            self.metric_store[name].append(metric)
            
            # Store in database
            cursor = self.db_conn.cursor()
            cursor.execute("""
                INSERT INTO metrics (name, value, timestamp, source, metric_type, tags, unit)
                VALUES (?, ?, ?, ?, ?, ?, ?)
            """, (
                metric.name, metric.value, metric.timestamp.isoformat(),
                metric.source, metric.metric_type.value,
                json.dumps(metric.tags) if metric.tags else None,
                metric.unit
            ))
            self.db_conn.commit()
        
        logger.debug(f"Collected metric: {name} = {value} ({unit or 'no unit'})")
    
    def register_alert_callback(self, callback: Callable[[Alert], None]):
        """Register a callback for alert notifications"""
        self.alert_callbacks.append(callback)
    
    def trigger_alert(self, metric_name: str, severity: AlertSeverity, 
                     message: str, value: float, threshold: float,
                     tags: Optional[Dict[str, str]] = None):
        """Trigger an alert"""
        alert = Alert(
            id=secrets.token_urlsafe(16),
            metric_name=metric_name,
            severity=severity,
            message=message,
            timestamp=datetime.utcnow(),
            value=value,
            threshold=threshold,
            tags=tags
        )
        
        with self.lock:
            # Add to in-memory buffer
            self.alerts_buffer.append(alert)
            
            # Store in database
            cursor = self.db_conn.cursor()
            cursor.execute("""
                INSERT INTO alerts (id, metric_name, severity, message, timestamp, value, threshold, tags)
                VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """, (
                alert.id, alert.metric_name, alert.severity.value, alert.message,
                alert.timestamp.isoformat(), alert.value, alert.threshold,
                json.dumps(alert.tags) if alert.tags else None
            ))
            self.db_conn.commit()
        
        # Call registered callbacks
        for callback in self.alert_callbacks:
            try:
                callback(alert)
            except Exception as e:
                logger.error(f"Alert callback failed: {e}")
        
        logger.warning(f"Alert triggered: {severity.value.upper()} - {message} (value: {value}, threshold: {threshold})")
    
    def get_recent_metrics(self, name: str, minutes: int = 60) -> List[Metric]:
        """Get recent metrics for a specific name"""
        cutoff_time = datetime.utcnow() - timedelta(minutes=minutes)
        
        with self.lock:
            return [m for m in self.metric_store[name] if m.timestamp >= cutoff_time]
    
    def get_metrics_summary(self, name: str, minutes: int = 60) -> Dict[str, Any]:
        """Get statistical summary of metrics"""
        metrics = self.get_recent_metrics(name, minutes)
        if not metrics:
            return {}
        
        values = [m.value for m in metrics]
        timestamps = [m.timestamp for m in metrics]
        
        return {
            'count': len(values),
            'mean': statistics.mean(values),
            'median': statistics.median(values),
            'std_dev': statistics.stdev(values) if len(values) > 1 else 0,
            'min': min(values),
            'max': max(values),
            'first_timestamp': min(timestamps),
            'last_timestamp': max(timestamps),
            'trend': 'increasing' if len(values) > 1 and values[-1] > values[0] else 'decreasing'
        }
    
    def get_alerts(self, hours: int = 24, severity: Optional[AlertSeverity] = None) -> List[Alert]:
        """Get recent alerts"""
        cutoff_time = datetime.utcnow() - timedelta(hours=hours)
        
        with self.lock:
            alerts = [a for a in self.alerts_buffer if a.timestamp >= cutoff_time]
        
        if severity:
            alerts = [a for a in alerts if a.severity == severity]
        
        return alerts
    
    def get_system_metrics(self) -> Dict[str, float]:
        """Get system-level metrics"""
        cpu_percent = psutil.cpu_percent(interval=1)
        memory_percent = psutil.virtual_memory().percent
        disk_percent = psutil.disk_usage('/').percent if hasattr(psutil, 'disk_usage') else 0
        
        # Get GPU metrics if available
        gpu_percent = 0
        gpu_memory_percent = 0
        try:
            gpus = GPUtil.getGPUs()
            if gpus:
                gpu = gpus[0]  # Use first GPU
                gpu_percent = gpu.load * 100
                gpu_memory_percent = gpu.memoryUtil * 100
        except Exception as e:
            # GPU not available or GPUtil not installed
            self.logger.debug(f"GPU monitoring unavailable: {e}")

        return {
            'cpu_percent': cpu_percent,
            'memory_percent': memory_percent,
            'disk_percent': disk_percent,
            'gpu_percent': gpu_percent,
            'gpu_memory_percent': gpu_memory_percent,
            'process_count': len(psutil.pids()),
            'network_io_mb': psutil.net_io_counters().bytes_sent / (1024*1024) + psutil.net_io_counters().bytes_recv / (1024*1024)
        }


class AnalyticsEngine:
    """Performs advanced analytics on collected metrics"""
    
    def __init__(self, metrics_collector: MetricsCollector):
        self.collector = metrics_collector
        self.anomaly_detectors = {}
        self.trend_analyzers = {}
        self.correlation_analyzers = {}
    
    def detect_anomalies(self, metric_name: str, method: str = 'zscore', threshold: float = 2.0) -> List[Metric]:
        """Detect anomalies in a metric using various methods"""
        metrics = self.collector.get_recent_metrics(metric_name, minutes=120)  # Last 2 hours
        if len(metrics) < 10:  # Need sufficient data points
            return []
        
        values = np.array([m.value for m in metrics])
        
        if method == 'zscore':
            z_scores = np.abs(stats.zscore(values))
            anomaly_indices = np.where(z_scores > threshold)[0]
        elif method == 'iqr':
            Q1 = np.percentile(values, 25)
            Q3 = np.percentile(values, 75)
            IQR = Q3 - Q1
            lower_bound = Q1 - 1.5 * IQR
            upper_bound = Q3 + 1.5 * IQR
            anomaly_indices = np.where((values < lower_bound) | (values > upper_bound))[0]
        else:
            raise ValueError(f"Unknown anomaly detection method: {method}")
        
        anomalies = [metrics[i] for i in anomaly_indices]
        return anomalies
    
    def analyze_trends(self, metric_name: str, window_minutes: int = 60) -> Dict[str, Any]:
        """Analyze trends in a metric over time"""
        metrics = self.collector.get_recent_metrics(metric_name, minutes=window_minutes)
        if len(metrics) < 2:
            return {'trend': 'insufficient_data', 'slope': 0, 'confidence': 0}
        
        values = [m.value for m in metrics]
        timestamps = [(m.timestamp - metrics[0].timestamp).total_seconds() for m in metrics]
        
        # Calculate linear regression
        slope, intercept, r_value, p_value, std_err = stats.linregress(timestamps, values)
        
        trend_direction = 'increasing' if slope > 0 else 'decreasing' if slope < 0 else 'stable'
        
        return {
            'trend': trend_direction,
            'slope': slope,
            'confidence': r_value ** 2,  # R-squared value
            'p_value': p_value,
            'std_error': std_err,
            'data_points': len(values)
        }
    
    def correlate_metrics(self, metric1: str, metric2: str, minutes: int = 60) -> Dict[str, Any]:
        """Calculate correlation between two metrics"""
        metrics1 = self.collector.get_recent_metrics(metric1, minutes)
        metrics2 = self.collector.get_recent_metrics(metric2, minutes)
        
        # Align timestamps
        df1 = pd.DataFrame([(m.timestamp, m.value) for m in metrics1], columns=['timestamp', 'value1'])
        df2 = pd.DataFrame([(m.timestamp, m.value) for m in metrics2], columns=['timestamp', 'value2'])
        
        # Merge on timestamp (approximate alignment)
        merged = pd.merge_asof(df1.sort_values('timestamp'), df2.sort_values('timestamp'), 
                              on='timestamp', tolerance=pd.Timedelta(seconds=30), direction='nearest')
        
        if len(merged) < 2:
            return {'correlation': 0, 'p_value': 1, 'sample_size': len(merged)}
        
        correlation, p_value = stats.pearsonr(merged['value1'], merged['value2'])
        
        return {
            'correlation': correlation,
            'p_value': p_value,
            'sample_size': len(merged),
            'significant': p_value < 0.05
        }
    
    def predict_future_values(self, metric_name: str, periods: int = 10) -> List[float]:
        """Simple prediction using linear extrapolation"""
        metrics = self.collector.get_recent_metrics(metric_name, minutes=60)
        if len(metrics) < 5:
            return [m.value for m in metrics[-periods:]] if metrics else []
        
        values = [m.value for m in metrics]
        timestamps = [(m.timestamp - metrics[0].timestamp).total_seconds() for m in metrics]
        
        # Calculate linear trend
        slope, intercept = np.polyfit(timestamps, values, 1)
        
        # Predict future values
        last_timestamp = timestamps[-1]
        future_values = []
        for i in range(1, periods + 1):
            future_time = last_timestamp + (i * 60)  # Assume 1-minute intervals
            predicted_value = slope * future_time + intercept
            future_values.append(predicted_value)
        
        return future_values


class DashboardGenerator:
    """Generates visual dashboards and reports"""
    
    def __init__(self, analytics_engine: AnalyticsEngine):
        self.analytics = analytics_engine
        self.collector = analytics_engine.collector
    
    def generate_performance_dashboard(self, output_path: str = "dashboard.html"):
        """Generate a performance dashboard"""
        # Create subplots
        fig = make_subplots(
            rows=3, cols=2,
            subplot_titles=('CPU Usage', 'Memory Usage', 'Disk Usage', 
                          'Metric Trends', 'Correlations', 'Anomalies'),
            specs=[[{"secondary_y": False}, {"secondary_y": False}],
                   [{"secondary_y": False}, {"secondary_y": False}],
                   [{"secondary_y": False}, {"secondary_y": False}]]
        )
        
        # Add system metrics
        system_metrics = self.collector.get_system_metrics()
        
        # CPU Usage
        fig.add_trace(
            go.Scatter(x=[datetime.now()], y=[system_metrics['cpu_percent']], 
                      mode='lines+markers', name='CPU %'),
            row=1, col=1
        )
        
        # Memory Usage
        fig.add_trace(
            go.Scatter(x=[datetime.now()], y=[system_metrics['memory_percent']], 
                      mode='lines+markers', name='Memory %'),
            row=1, col=2
        )
        
        # Disk Usage
        fig.add_trace(
            go.Scatter(x=[datetime.now()], y=[system_metrics['disk_percent']], 
                      mode='lines+markers', name='Disk %'),
            row=2, col=1
        )
        
        # Save the dashboard
        fig.update_layout(height=800, showlegend=True, title_text="AirOne Professional Monitoring Dashboard")
        fig.write_html(output_path)
        
        logger.info(f"Performance dashboard saved to {output_path}")
    
    def generate_metric_report(self, metric_name: str, days: int = 7) -> str:
        """Generate a detailed report for a specific metric"""
        metrics = self.collector.get_recent_metrics(metric_name, minutes=days*24*60)
        summary = self.collector.get_metrics_summary(metric_name, minutes=days*24*60)
        
        # Analyze trends
        trend_analysis = self.analytics.analyze_trends(metric_name, window_minutes=days*24*60)
        
        # Detect anomalies
        anomalies = self.analytics.detect_anomalies(metric_name)
        
        report = f"""
# Metric Report: {metric_name}

## Summary Statistics
- Count: {summary.get('count', 0)}
- Mean: {summary.get('mean', 0):.2f}
- Median: {summary.get('median', 0):.2f}
- Std Dev: {summary.get('std_dev', 0):.2f}
- Min: {summary.get('min', 0):.2f}
- Max: {summary.get('max', 0):.2f}

## Trend Analysis
- Direction: {trend_analysis.get('trend', 'N/A')}
- Slope: {trend_analysis.get('slope', 0):.4f}
- Confidence (R²): {trend_analysis.get('confidence', 0):.4f}

## Anomalies Detected
- Total Anomalies: {len(anomalies)}

## Data Range
- From: {summary.get('first_timestamp', 'N/A')}
- To: {summary.get('last_timestamp', 'N/A')}
        """
        
        return report
    
    def export_to_csv(self, metric_name: str, output_path: str, days: int = 7):
        """Export metric data to CSV"""
        metrics = self.collector.get_recent_metrics(metric_name, minutes=days*24*60)
        
        with open(output_path, 'w', newline='') as csvfile:
            fieldnames = ['timestamp', 'value', 'source', 'metric_type', 'unit']
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            
            writer.writeheader()
            for metric in metrics:
                writer.writerow({
                    'timestamp': metric.timestamp.isoformat(),
                    'value': metric.value,
                    'source': metric.source,
                    'metric_type': metric.metric_type.value,
                    'unit': metric.unit
                })
        
        logger.info(f"Data exported to {output_path}")


class AlertManager:
    """Manages alert rules and notifications"""
    
    def __init__(self, metrics_collector: MetricsCollector):
        self.collector = metrics_collector
        self.rules = []
        self.active_alerts = {}
        self.notification_callbacks = []
    
    def add_rule(self, metric_name: str, condition: str, threshold: float, 
                 severity: AlertSeverity, message_template: str):
        """Add an alert rule"""
        rule = {
            'metric_name': metric_name,
            'condition': condition,  # 'gt', 'lt', 'eq', 'gte', 'lte'
            'threshold': threshold,
            'severity': severity,
            'message_template': message_template
        }
        self.rules.append(rule)
        logger.info(f"Added alert rule: {metric_name} {condition} {threshold}")
    
    def evaluate_rules(self):
        """Evaluate all rules against recent metrics"""
        for rule in self.rules:
            metric_name = rule['metric_name']
            recent_metrics = self.collector.get_recent_metrics(metric_name, minutes=5)  # Last 5 minutes
            
            if not recent_metrics:
                continue
            
            latest_value = recent_metrics[-1].value
            
            # Check condition
            condition_met = False
            if rule['condition'] == 'gt' and latest_value > rule['threshold']:
                condition_met = True
            elif rule['condition'] == 'lt' and latest_value < rule['threshold']:
                condition_met = True
            elif rule['condition'] == 'gte' and latest_value >= rule['threshold']:
                condition_met = True
            elif rule['condition'] == 'lte' and latest_value <= rule['threshold']:
                condition_met = True
            elif rule['condition'] == 'eq' and latest_value == rule['threshold']:
                condition_met = True
            
            if condition_met:
                # Check if we already have an active alert for this rule
                alert_key = f"{metric_name}_{rule['condition']}_{rule['threshold']}"
                if alert_key not in self.active_alerts:
                    # Create and trigger alert
                    message = rule['message_template'].format(
                        value=latest_value,
                        threshold=rule['threshold'],
                        metric=metric_name
                    )
                    
                    self.collector.trigger_alert(
                        metric_name=metric_name,
                        severity=rule['severity'],
                        message=message,
                        value=latest_value,
                        threshold=rule['threshold']
                    )
                    
                    # Track active alert
                    self.active_alerts[alert_key] = datetime.utcnow()
                else:
                    # Update the timestamp of the active alert
                    self.active_alerts[alert_key] = datetime.utcnow()
            else:
                # Clear the alert if condition is no longer met
                alert_key = f"{metric_name}_{rule['condition']}_{rule['threshold']}"
                if alert_key in self.active_alerts:
                    del self.active_alerts[alert_key]
    
    def add_notification_callback(self, callback: Callable[[Alert], None]):
        """Add a notification callback"""
        self.notification_callbacks.append(callback)
        self.collector.register_alert_callback(callback)


class MonitoringService:
    """Main monitoring service that orchestrates all components"""
    
    def __init__(self):
        self.collector = MetricsCollector(retention_hours=24)
        self.analytics = AnalyticsEngine(self.collector)
        self.dashboard = DashboardGenerator(self.analytics)
        self.alert_manager = AlertManager(self.collector)
        self.running = False
        self.monitoring_thread = None
        
        # Add default alert rules
        self._setup_default_rules()
    
    def _setup_default_rules(self):
        """Setup default monitoring rules"""
        # CPU usage > 80% - Warning
        self.alert_manager.add_rule(
            metric_name='system_cpu_percent',
            condition='gt',
            threshold=80.0,
            severity=AlertSeverity.WARNING,
            message_template='High CPU usage detected: {value:.2f}% (threshold: {threshold}%)'
        )
        
        # Memory usage > 90% - Critical
        self.alert_manager.add_rule(
            metric_name='system_memory_percent',
            condition='gt',
            threshold=90.0,
            severity=AlertSeverity.CRITICAL,
            message_template='Critical memory usage: {value:.2f}% (threshold: {threshold}%)'
        )
        
        # Low battery < 20% - Warning
        self.alert_manager.add_rule(
            metric_name='telemetry_battery_level',
            condition='lt',
            threshold=20.0,
            severity=AlertSeverity.WARNING,
            message_template='Low battery level: {value:.2f}% (threshold: {threshold}%)'
        )
    
    def start(self):
        """Start the monitoring service"""
        self.running = True
        self.monitoring_thread = threading.Thread(target=self._monitoring_loop, daemon=True)
        self.monitoring_thread.start()
        logger.info("Monitoring service started")
    
    def stop(self):
        """Stop the monitoring service"""
        self.running = False
        if self.monitoring_thread:
            self.monitoring_thread.join(timeout=5)
        logger.info("Monitoring service stopped")
    
    def _monitoring_loop(self):
        """Main monitoring loop"""
        while self.running:
            try:
                # Collect system metrics
                system_metrics = self.collector.get_system_metrics()
                for metric_name, value in system_metrics.items():
                    self.collector.collect_metric(
                        name=f"system_{metric_name}",
                        value=value,
                        source="system_monitor",
                        metric_type=MetricType.SYSTEM
                    )
                
                # Evaluate alert rules
                self.alert_manager.evaluate_rules()
                
                # Sleep for 30 seconds before next iteration
                time.sleep(30)
                
            except Exception as e:
                logger.error(f"Monitoring loop error: {e}")
                time.sleep(5)  # Brief pause before retrying
    
    def collect_custom_metric(self, name: str, value: float, source: str = "custom",
                             metric_type: MetricType = MetricType.CUSTOM,
                             unit: Optional[str] = None,
                             tags: Optional[Dict[str, str]] = None):
        """Collect a custom metric"""
        self.collector.collect_metric(name, value, source, metric_type, unit, tags)
    
    def get_analytics_report(self, metric_name: str) -> Dict[str, Any]:
        """Get comprehensive analytics for a metric"""
        summary = self.collector.get_metrics_summary(metric_name)
        trend = self.analytics.analyze_trends(metric_name)
        anomalies = self.analytics.detect_anomalies(metric_name)
        predictions = self.analytics.predict_future_values(metric_name, periods=5)
        
        return {
            'summary': summary,
            'trend': trend,
            'anomalies_count': len(anomalies),
            'predictions': predictions,
            'last_updated': datetime.utcnow().isoformat()
        }


# Example usage and testing
if __name__ == "__main__":
    # Initialize monitoring service
    monitoring_service = MonitoringService()
    monitoring_service.start()
    
    print("📊 Monitoring service started...")
    
    # Simulate collecting some metrics
    import random
    
    for i in range(10):
        # Simulate telemetry data
        battery_level = random.uniform(15, 100)
        signal_strength = random.uniform(5, 100)
        temperature = random.uniform(-10, 50)
        
        monitoring_service.collect_custom_metric(
            name="telemetry_battery_level",
            value=battery_level,
            source="satellite_simulator",
            metric_type=MetricType.APPLICATION,
            unit="%"
        )
        
        monitoring_service.collect_custom_metric(
            name="telemetry_signal_strength",
            value=signal_strength,
            source="satellite_simulator",
            metric_type=MetricType.APPLICATION,
            unit="dBm"
        )
        
        monitoring_service.collect_custom_metric(
            name="telemetry_temperature",
            value=temperature,
            source="satellite_simulator",
            metric_type=MetricType.APPLICATION,
            unit="°C"
        )
        
        print(f"Collected metrics - Battery: {battery_level:.2f}%, Signal: {signal_strength:.2f}dBm, Temp: {temperature:.2f}°C")
        time.sleep(2)
    
    # Get analytics report
    print("\n📈 Getting analytics report for battery level...")
    report = monitoring_service.get_analytics_report("telemetry_battery_level")
    print(json.dumps(report, indent=2, default=str))
    
    # Generate a dashboard
    print("\n📊 Generating dashboard...")
    monitoring_service.dashboard.generate_performance_dashboard("test_dashboard.html")
    
    # Get recent alerts
    print("\n🚨 Recent alerts:")
    alerts = monitoring_service.collector.get_alerts(hours=1)
    for alert in alerts:
        print(f"  {alert.severity.value.upper()}: {alert.message} at {alert.timestamp}")
    
    # Stop the service
    time.sleep(5)  # Allow time for final metrics collection
    monitoring_service.stop()
    print("\n✅ Monitoring service stopped")